name: Python CI
 
on:
  push:
    branches:
      - main  # Run on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Run on pull requests targeting the 'main' branch
 
jobs:
  test:
    runs-on: ubuntu-latest  # Run on an Ubuntu machine
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository
   
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set the Python version to 3.8
   
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt
   
    - name: Run tests
      run: |
        python -m unittest discover -s flask_app/tests  # Run your unit tests
 
has context menu